/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Stock' : null } |
  { 'Cash' : null } |
  { 'Forex' : null } |
  { 'Crypto' : null };
export interface Holding {
  'currentPrice' : number,
  'assetId' : bigint,
  'totalValue' : number,
  'name' : string,
  'gainLoss' : number,
  'totalCost' : number,
  'averageCost' : number,
  'currency' : string,
  'quantity' : number,
  'category' : Category,
  'gainLossPercent' : number,
  'symbol' : string,
}
export interface PortfolioSnapshot {
  'id' : bigint,
  'totalValue' : number,
  'date' : bigint,
  'createdAt' : bigint,
}
export interface PortfolioSummary {
  'totalValue' : number,
  'totalCost' : number,
  'dailyChange' : number,
  'totalGainLoss' : number,
  'allocation' : Array<
    { 'value' : number, 'category' : Category, 'percentage' : number }
  >,
  'totalGainLossPercent' : number,
}
export interface Public {
  'baseCurrency' : string,
  'displayName' : string,
  'createdAt' : bigint,
  'user' : Principal,
}
export interface Public__1 {
  'id' : bigint,
  'name' : string,
  'note' : string,
  'createdAt' : bigint,
  'currency' : string,
  'category' : Category,
  'manualPrice' : number,
  'symbol' : string,
}
export interface StockPrice {
  'ok' : boolean,
  'change24h' : number,
  'price' : number,
  'symbol' : string,
}
export interface StockSearchResult {
  'name' : string,
  'exchange' : string,
  'symbol' : string,
}
export interface Transaction {
  'id' : bigint,
  'fee' : number,
  'assetId' : bigint,
  'date' : bigint,
  'note' : string,
  'createdAt' : bigint,
  'quantity' : number,
  'txType' : TxType,
  'price' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type TxType = { 'Buy' : null } |
  { 'Withdraw' : null } |
  { 'Deposit' : null } |
  { 'Sell' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAsset' : ActorMethod<[Public__1], bigint>,
  'addSnapshot' : ActorMethod<[PortfolioSnapshot], bigint>,
  'addTransaction' : ActorMethod<[Transaction], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAsset' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getAsset' : ActorMethod<[bigint], [] | [Public__1]>,
  'getAssets' : ActorMethod<[], Array<Public__1>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Public]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHoldings' : ActorMethod<[], Array<Holding>>,
  'getPortfolioSummary' : ActorMethod<[], PortfolioSummary>,
  'getProfile' : ActorMethod<[], [] | [Public]>,
  'getSnapshots' : ActorMethod<[bigint, bigint], Array<PortfolioSnapshot>>,
  'getStockPrice' : ActorMethod<[string], StockPrice>,
  'getTransaction' : ActorMethod<[bigint], [] | [Transaction]>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Public]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[Public], undefined>,
  'searchStocks' : ActorMethod<[string], Array<StockSearchResult>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transformSearch' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAsset' : ActorMethod<[Public__1], undefined>,
  'updateProfile' : ActorMethod<[Public], undefined>,
  'updateTransaction' : ActorMethod<[Transaction], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];