/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'Stock' : IDL.Null,
  'RealEstate' : IDL.Null,
  'Cash' : IDL.Null,
  'Commodity' : IDL.Null,
  'Forex' : IDL.Null,
  'Crypto' : IDL.Null,
});
export const Public__1 = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'currency' : IDL.Text,
  'category' : Category,
  'manualPrice' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const PortfolioSnapshot = IDL.Record({
  'id' : IDL.Nat,
  'totalValue' : IDL.Float64,
  'date' : IDL.Int,
  'createdAt' : IDL.Int,
});
export const TxType = IDL.Variant({
  'Buy' : IDL.Null,
  'Withdraw' : IDL.Null,
  'Deposit' : IDL.Null,
  'Sell' : IDL.Null,
});
export const AddTransactionInput = IDL.Record({
  'id' : IDL.Nat,
  'fee' : IDL.Float64,
  'assetId' : IDL.Nat,
  'date' : IDL.Int,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'currency' : IDL.Text,
  'quantity' : IDL.Float64,
  'txType' : TxType,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Public__2 = IDL.Record({
  'id' : IDL.Nat,
  'totalValue' : IDL.Float64,
  'date' : IDL.Int,
  'createdAt' : IDL.Int,
});
export const Public__3 = IDL.Record({
  'id' : IDL.Nat,
  'fee' : IDL.Float64,
  'assetId' : IDL.Nat,
  'date' : IDL.Int,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'currency' : IDL.Text,
  'quantity' : IDL.Float64,
  'txType' : TxType,
  'price' : IDL.Float64,
});
export const Public = IDL.Record({
  'baseCurrency' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'user' : IDL.Principal,
});
export const PortfolioExport = IDL.Record({
  'assets' : IDL.Vec(Public__1),
  'snapshots' : IDL.Vec(Public__2),
  'exportedAt' : IDL.Int,
  'transactions' : IDL.Vec(Public__3),
  'profile' : IDL.Opt(Public),
});
export const Holding = IDL.Record({
  'currentPrice' : IDL.Float64,
  'assetId' : IDL.Nat,
  'totalValue' : IDL.Float64,
  'name' : IDL.Text,
  'gainLoss' : IDL.Float64,
  'totalCost' : IDL.Float64,
  'averageCost' : IDL.Float64,
  'currency' : IDL.Text,
  'quantity' : IDL.Float64,
  'category' : Category,
  'gainLossPercent' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const MetalPrice = IDL.Record({
  'currency' : IDL.Text,
  'timestamp' : IDL.Int,
  'price' : IDL.Float64,
});
export const PortfolioSummary = IDL.Record({
  'totalValue' : IDL.Float64,
  'totalCost' : IDL.Float64,
  'dailyChange' : IDL.Float64,
  'totalGainLoss' : IDL.Float64,
  'allocation' : IDL.Vec(
    IDL.Record({
      'value' : IDL.Float64,
      'category' : Category,
      'percentage' : IDL.Float64,
    })
  ),
  'totalGainLossPercent' : IDL.Float64,
});
export const StockPrice = IDL.Record({
  'ok' : IDL.Bool,
  'change24h' : IDL.Float64,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'fee' : IDL.Float64,
  'assetId' : IDL.Nat,
  'date' : IDL.Int,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'currency' : IDL.Text,
  'quantity' : IDL.Float64,
  'txType' : TxType,
  'price' : IDL.Float64,
});
export const AssetImport = IDL.Record({
  'name' : IDL.Text,
  'note' : IDL.Text,
  'currency' : IDL.Text,
  'category' : Category,
  'manualPrice' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const TransactionImport = IDL.Record({
  'fee' : IDL.Float64,
  'assetId' : IDL.Nat,
  'date' : IDL.Int,
  'note' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Float64,
  'txType' : TxType,
  'price' : IDL.Float64,
});
export const PortfolioImportInput = IDL.Record({
  'assets' : IDL.Vec(AssetImport),
  'transactions' : IDL.Vec(TransactionImport),
});
export const ImportResult = IDL.Record({
  'assetsSkipped' : IDL.Nat,
  'assetsImported' : IDL.Nat,
  'transactionsImported' : IDL.Nat,
});
export const StockSearchResult = IDL.Record({
  'name' : IDL.Text,
  'exchange' : IDL.Text,
  'symbol' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAsset' : IDL.Func([Public__1], [IDL.Nat], []),
  'addSnapshot' : IDL.Func([PortfolioSnapshot], [IDL.Nat], []),
  'addTransaction' : IDL.Func([AddTransactionInput], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAsset' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'exportPortfolioData' : IDL.Func([], [PortfolioExport], ['query']),
  'getAsset' : IDL.Func([IDL.Nat], [IDL.Opt(Public__1)], ['query']),
  'getAssets' : IDL.Func([], [IDL.Vec(Public__1)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Public)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExchangeRates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      [],
    ),
  'getHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
  'getHoldingsInCurrency' : IDL.Func([IDL.Text], [IDL.Vec(Holding)], ['query']),
  'getMetalPrice' : IDL.Func([], [MetalPrice], []),
  'getMetalPriceBySymbol' : IDL.Func([IDL.Text], [MetalPrice], []),
  'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
  'getPortfolioSummaryInCurrency' : IDL.Func(
      [IDL.Text],
      [PortfolioSummary],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [IDL.Opt(Public)], ['query']),
  'getSnapshots' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(PortfolioSnapshot)],
      ['query'],
    ),
  'getStockPrice' : IDL.Func([IDL.Text], [StockPrice], []),
  'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Public)], ['query']),
  'importPortfolioData' : IDL.Func([PortfolioImportInput], [ImportResult], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([Public], [], []),
  'searchStocks' : IDL.Func([IDL.Text], [IDL.Vec(StockSearchResult)], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformMetal' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformSearch' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAsset' : IDL.Func([Public__1], [], []),
  'updateProfile' : IDL.Func([Public], [], []),
  'updateTransaction' : IDL.Func([AddTransactionInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'Stock' : IDL.Null,
    'RealEstate' : IDL.Null,
    'Cash' : IDL.Null,
    'Commodity' : IDL.Null,
    'Forex' : IDL.Null,
    'Crypto' : IDL.Null,
  });
  const Public__1 = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'currency' : IDL.Text,
    'category' : Category,
    'manualPrice' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const PortfolioSnapshot = IDL.Record({
    'id' : IDL.Nat,
    'totalValue' : IDL.Float64,
    'date' : IDL.Int,
    'createdAt' : IDL.Int,
  });
  const TxType = IDL.Variant({
    'Buy' : IDL.Null,
    'Withdraw' : IDL.Null,
    'Deposit' : IDL.Null,
    'Sell' : IDL.Null,
  });
  const AddTransactionInput = IDL.Record({
    'id' : IDL.Nat,
    'fee' : IDL.Float64,
    'assetId' : IDL.Nat,
    'date' : IDL.Int,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'currency' : IDL.Text,
    'quantity' : IDL.Float64,
    'txType' : TxType,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Public__2 = IDL.Record({
    'id' : IDL.Nat,
    'totalValue' : IDL.Float64,
    'date' : IDL.Int,
    'createdAt' : IDL.Int,
  });
  const Public__3 = IDL.Record({
    'id' : IDL.Nat,
    'fee' : IDL.Float64,
    'assetId' : IDL.Nat,
    'date' : IDL.Int,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'currency' : IDL.Text,
    'quantity' : IDL.Float64,
    'txType' : TxType,
    'price' : IDL.Float64,
  });
  const Public = IDL.Record({
    'baseCurrency' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'user' : IDL.Principal,
  });
  const PortfolioExport = IDL.Record({
    'assets' : IDL.Vec(Public__1),
    'snapshots' : IDL.Vec(Public__2),
    'exportedAt' : IDL.Int,
    'transactions' : IDL.Vec(Public__3),
    'profile' : IDL.Opt(Public),
  });
  const Holding = IDL.Record({
    'currentPrice' : IDL.Float64,
    'assetId' : IDL.Nat,
    'totalValue' : IDL.Float64,
    'name' : IDL.Text,
    'gainLoss' : IDL.Float64,
    'totalCost' : IDL.Float64,
    'averageCost' : IDL.Float64,
    'currency' : IDL.Text,
    'quantity' : IDL.Float64,
    'category' : Category,
    'gainLossPercent' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const MetalPrice = IDL.Record({
    'currency' : IDL.Text,
    'timestamp' : IDL.Int,
    'price' : IDL.Float64,
  });
  const PortfolioSummary = IDL.Record({
    'totalValue' : IDL.Float64,
    'totalCost' : IDL.Float64,
    'dailyChange' : IDL.Float64,
    'totalGainLoss' : IDL.Float64,
    'allocation' : IDL.Vec(
      IDL.Record({
        'value' : IDL.Float64,
        'category' : Category,
        'percentage' : IDL.Float64,
      })
    ),
    'totalGainLossPercent' : IDL.Float64,
  });
  const StockPrice = IDL.Record({
    'ok' : IDL.Bool,
    'change24h' : IDL.Float64,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'fee' : IDL.Float64,
    'assetId' : IDL.Nat,
    'date' : IDL.Int,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'currency' : IDL.Text,
    'quantity' : IDL.Float64,
    'txType' : TxType,
    'price' : IDL.Float64,
  });
  const AssetImport = IDL.Record({
    'name' : IDL.Text,
    'note' : IDL.Text,
    'currency' : IDL.Text,
    'category' : Category,
    'manualPrice' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const TransactionImport = IDL.Record({
    'fee' : IDL.Float64,
    'assetId' : IDL.Nat,
    'date' : IDL.Int,
    'note' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Float64,
    'txType' : TxType,
    'price' : IDL.Float64,
  });
  const PortfolioImportInput = IDL.Record({
    'assets' : IDL.Vec(AssetImport),
    'transactions' : IDL.Vec(TransactionImport),
  });
  const ImportResult = IDL.Record({
    'assetsSkipped' : IDL.Nat,
    'assetsImported' : IDL.Nat,
    'transactionsImported' : IDL.Nat,
  });
  const StockSearchResult = IDL.Record({
    'name' : IDL.Text,
    'exchange' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAsset' : IDL.Func([Public__1], [IDL.Nat], []),
    'addSnapshot' : IDL.Func([PortfolioSnapshot], [IDL.Nat], []),
    'addTransaction' : IDL.Func([AddTransactionInput], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAsset' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'exportPortfolioData' : IDL.Func([], [PortfolioExport], ['query']),
    'getAsset' : IDL.Func([IDL.Nat], [IDL.Opt(Public__1)], ['query']),
    'getAssets' : IDL.Func([], [IDL.Vec(Public__1)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Public)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExchangeRates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        [],
      ),
    'getHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
    'getHoldingsInCurrency' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Holding)],
        ['query'],
      ),
    'getMetalPrice' : IDL.Func([], [MetalPrice], []),
    'getMetalPriceBySymbol' : IDL.Func([IDL.Text], [MetalPrice], []),
    'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
    'getPortfolioSummaryInCurrency' : IDL.Func(
        [IDL.Text],
        [PortfolioSummary],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(Public)], ['query']),
    'getSnapshots' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(PortfolioSnapshot)],
        ['query'],
      ),
    'getStockPrice' : IDL.Func([IDL.Text], [StockPrice], []),
    'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Public)], ['query']),
    'importPortfolioData' : IDL.Func(
        [PortfolioImportInput],
        [ImportResult],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([Public], [], []),
    'searchStocks' : IDL.Func([IDL.Text], [IDL.Vec(StockSearchResult)], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformMetal' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformSearch' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAsset' : IDL.Func([Public__1], [], []),
    'updateProfile' : IDL.Func([Public], [], []),
    'updateTransaction' : IDL.Func([AddTransactionInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };