/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Public__2 {
    id: bigint;
    totalValue: number;
    date: bigint;
    createdAt: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransactionImport {
    fee: number;
    assetId: bigint;
    date: bigint;
    note: string;
    currency: string;
    quantity: number;
    txType: TxType;
    price: number;
}
export interface PortfolioImportInput {
    assets: Array<AssetImport>;
    transactions: Array<TransactionImport>;
}
export interface PortfolioSummary {
    totalValue: number;
    totalCost: number;
    dailyChange: number;
    totalGainLoss: number;
    allocation: Array<{
        value: number;
        category: Category;
        percentage: number;
    }>;
    totalGainLossPercent: number;
}
export interface StockSearchResult {
    name: string;
    exchange: string;
    symbol: string;
}
export interface Public__3 {
    id: bigint;
    fee: number;
    assetId: bigint;
    date: bigint;
    note: string;
    createdAt: bigint;
    currency: string;
    quantity: number;
    txType: TxType;
    price: number;
}
export interface Public {
    baseCurrency: string;
    displayName: string;
    createdAt: bigint;
    user: Principal;
}
export interface PortfolioExport {
    assets: Array<Public__1>;
    snapshots: Array<Public__2>;
    exportedAt: bigint;
    transactions: Array<Public__3>;
    profile?: Public;
}
export interface MetalPrice {
    currency: string;
    timestamp: bigint;
    price: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface Transaction {
    id: bigint;
    fee: number;
    assetId: bigint;
    date: bigint;
    note: string;
    createdAt: bigint;
    currency: string;
    quantity: number;
    txType: TxType;
    price: number;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ImportResult {
    assetsSkipped: bigint;
    assetsImported: bigint;
    transactionsImported: bigint;
}
export interface StockPrice {
    ok: boolean;
    change24h: number;
    price: number;
    symbol: string;
}
export interface Holding {
    currentPrice: number;
    assetId: bigint;
    totalValue: number;
    name: string;
    gainLoss: number;
    totalCost: number;
    averageCost: number;
    currency: string;
    quantity: number;
    category: Category;
    gainLossPercent: number;
    symbol: string;
}
export interface PortfolioSnapshot {
    id: bigint;
    totalValue: number;
    date: bigint;
    createdAt: bigint;
}
export interface Public__1 {
    id: bigint;
    name: string;
    note: string;
    createdAt: bigint;
    currency: string;
    category: Category;
    manualPrice: number;
    symbol: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface AddTransactionInput {
    id: bigint;
    fee: number;
    assetId: bigint;
    date: bigint;
    note: string;
    createdAt: bigint;
    currency: string;
    quantity: number;
    txType: TxType;
    price: number;
}
export interface AssetImport {
    name: string;
    note: string;
    currency: string;
    category: Category;
    manualPrice: number;
    symbol: string;
}
export enum Category {
    Stock = "Stock",
    RealEstate = "RealEstate",
    Cash = "Cash",
    Commodity = "Commodity",
    Forex = "Forex",
    Crypto = "Crypto"
}
export enum TxType {
    Buy = "Buy",
    Withdraw = "Withdraw",
    Deposit = "Deposit",
    Sell = "Sell"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addAsset(asset: Public__1): Promise<bigint>;
    addSnapshot(snapshot: PortfolioSnapshot): Promise<bigint>;
    addTransaction(tx: AddTransactionInput): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAsset(id: bigint): Promise<void>;
    deleteTransaction(id: bigint): Promise<void>;
    exportPortfolioData(): Promise<PortfolioExport>;
    getAsset(id: bigint): Promise<Public__1 | null>;
    getAssets(): Promise<Array<Public__1>>;
    getCallerUserProfile(): Promise<Public | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExchangeRates(): Promise<Array<[string, number]>>;
    getHoldings(): Promise<Array<Holding>>;
    getHoldingsInCurrency(targetCurrency: string): Promise<Array<Holding>>;
    getMetalPrice(): Promise<MetalPrice>;
    getMetalPriceBySymbol(symbol: string): Promise<MetalPrice>;
    getPortfolioSummary(): Promise<PortfolioSummary>;
    getPortfolioSummaryInCurrency(targetCurrency: string): Promise<PortfolioSummary>;
    getProfile(): Promise<Public | null>;
    getSnapshots(startDate: bigint, endDate: bigint): Promise<Array<PortfolioSnapshot>>;
    getStockPrice(symbol: string): Promise<StockPrice>;
    getTransaction(id: bigint): Promise<Transaction | null>;
    getTransactions(): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<Public | null>;
    importPortfolioData(data: PortfolioImportInput): Promise<ImportResult>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: Public): Promise<void>;
    searchStocks(searchTerm: string): Promise<Array<StockSearchResult>>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    transformMetal(input: TransformationInput): Promise<TransformationOutput>;
    transformSearch(input: TransformationInput): Promise<TransformationOutput>;
    updateAsset(asset: Public__1): Promise<void>;
    updateProfile(profile: Public): Promise<void>;
    updateTransaction(tx: AddTransactionInput): Promise<void>;
}
import type { AddTransactionInput as _AddTransactionInput, AssetImport as _AssetImport, Category as _Category, Holding as _Holding, PortfolioExport as _PortfolioExport, PortfolioImportInput as _PortfolioImportInput, PortfolioSummary as _PortfolioSummary, Public as _Public, Public__1 as _Public__1, Public__2 as _Public__2, Public__3 as _Public__3, Transaction as _Transaction, TransactionImport as _TransactionImport, TxType as _TxType, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addAsset(arg0: Public__1): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAsset(to_candid_Public__1_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAsset(to_candid_Public__1_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSnapshot(arg0: PortfolioSnapshot): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSnapshot(arg0);
            return result;
        }
    }
    async addTransaction(arg0: AddTransactionInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_AddTransactionInput_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_AddTransactionInput_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAsset(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAsset(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async exportPortfolioData(): Promise<PortfolioExport> {
        if (this.processError) {
            try {
                const result = await this.actor.exportPortfolioData();
                return from_candid_PortfolioExport_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportPortfolioData();
            return from_candid_PortfolioExport_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAsset(arg0: bigint): Promise<Public__1 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAsset(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAsset(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssets(): Promise<Array<Public__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssets();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssets();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<Public | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExchangeRates(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExchangeRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExchangeRates();
            return result;
        }
    }
    async getHoldings(): Promise<Array<Holding>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHoldings();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHoldings();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHoldingsInCurrency(arg0: string): Promise<Array<Holding>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHoldingsInCurrency(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHoldingsInCurrency(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMetalPrice(): Promise<MetalPrice> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetalPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetalPrice();
            return result;
        }
    }
    async getMetalPriceBySymbol(arg0: string): Promise<MetalPrice> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetalPriceBySymbol(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetalPriceBySymbol(arg0);
            return result;
        }
    }
    async getPortfolioSummary(): Promise<PortfolioSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSummary();
                return from_candid_PortfolioSummary_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSummary();
            return from_candid_PortfolioSummary_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioSummaryInCurrency(arg0: string): Promise<PortfolioSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSummaryInCurrency(arg0);
                return from_candid_PortfolioSummary_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSummaryInCurrency(arg0);
            return from_candid_PortfolioSummary_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<Public | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSnapshots(arg0: bigint, arg1: bigint): Promise<Array<PortfolioSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSnapshots(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSnapshots(arg0, arg1);
            return result;
        }
    }
    async getStockPrice(arg0: string): Promise<StockPrice> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockPrice(arg0);
            return result;
        }
    }
    async getTransaction(arg0: bigint): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<Public | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async importPortfolioData(arg0: PortfolioImportInput): Promise<ImportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.importPortfolioData(to_candid_PortfolioImportInput_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importPortfolioData(to_candid_PortfolioImportInput_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: Public): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchStocks(arg0: string): Promise<Array<StockSearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStocks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStocks(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async transformMetal(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformMetal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformMetal(arg0);
            return result;
        }
    }
    async transformSearch(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformSearch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformSearch(arg0);
            return result;
        }
    }
    async updateAsset(arg0: Public__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAsset(to_candid_Public__1_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAsset(to_candid_Public__1_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProfile(arg0: Public): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return result;
        }
    }
    async updateTransaction(arg0: AddTransactionInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(to_candid_AddTransactionInput_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(to_candid_AddTransactionInput_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Category_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Holding_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Holding): Holding {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioExport_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioExport): PortfolioExport {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioSummary_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioSummary): PortfolioSummary {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Public__1_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Public__1): Public__1 {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Public__3_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Public__3): Public__3 {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TxType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxType): TxType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Public]): Public | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Public__1]): Public__1 | null {
    return value.length === 0 ? null : from_candid_Public__1_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assets: Array<_Public__1>;
    snapshots: Array<_Public__2>;
    exportedAt: bigint;
    transactions: Array<_Public__3>;
    profile: [] | [_Public];
}): {
    assets: Array<Public__1>;
    snapshots: Array<Public__2>;
    exportedAt: bigint;
    transactions: Array<Public__3>;
    profile?: Public;
} {
    return {
        assets: from_candid_vec_n13(_uploadFile, _downloadFile, value.assets),
        snapshots: value.snapshots,
        exportedAt: value.exportedAt,
        transactions: from_candid_vec_n18(_uploadFile, _downloadFile, value.transactions),
        profile: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    note: string;
    createdAt: bigint;
    currency: string;
    category: _Category;
    manualPrice: number;
    symbol: string;
}): {
    id: bigint;
    name: string;
    note: string;
    createdAt: bigint;
    currency: string;
    category: Category;
    manualPrice: number;
    symbol: string;
} {
    return {
        id: value.id,
        name: value.name,
        note: value.note,
        createdAt: value.createdAt,
        currency: value.currency,
        category: from_candid_Category_n16(_uploadFile, _downloadFile, value.category),
        manualPrice: value.manualPrice,
        symbol: value.symbol
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    fee: number;
    assetId: bigint;
    date: bigint;
    note: string;
    createdAt: bigint;
    currency: string;
    quantity: number;
    txType: _TxType;
    price: number;
}): {
    id: bigint;
    fee: number;
    assetId: bigint;
    date: bigint;
    note: string;
    createdAt: bigint;
    currency: string;
    quantity: number;
    txType: TxType;
    price: number;
} {
    return {
        id: value.id,
        fee: value.fee,
        assetId: value.assetId,
        date: value.date,
        note: value.note,
        createdAt: value.createdAt,
        currency: value.currency,
        quantity: value.quantity,
        txType: from_candid_TxType_n21(_uploadFile, _downloadFile, value.txType),
        price: value.price
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentPrice: number;
    assetId: bigint;
    totalValue: number;
    name: string;
    gainLoss: number;
    totalCost: number;
    averageCost: number;
    currency: string;
    quantity: number;
    category: _Category;
    gainLossPercent: number;
    symbol: string;
}): {
    currentPrice: number;
    assetId: bigint;
    totalValue: number;
    name: string;
    gainLoss: number;
    totalCost: number;
    averageCost: number;
    currency: string;
    quantity: number;
    category: Category;
    gainLossPercent: number;
    symbol: string;
} {
    return {
        currentPrice: value.currentPrice,
        assetId: value.assetId,
        totalValue: value.totalValue,
        name: value.name,
        gainLoss: value.gainLoss,
        totalCost: value.totalCost,
        averageCost: value.averageCost,
        currency: value.currency,
        quantity: value.quantity,
        category: from_candid_Category_n16(_uploadFile, _downloadFile, value.category),
        gainLossPercent: value.gainLossPercent,
        symbol: value.symbol
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalValue: number;
    totalCost: number;
    dailyChange: number;
    totalGainLoss: number;
    allocation: Array<{
        value: number;
        category: _Category;
        percentage: number;
    }>;
    totalGainLossPercent: number;
}): {
    totalValue: number;
    totalCost: number;
    dailyChange: number;
    totalGainLoss: number;
    allocation: Array<{
        value: number;
        category: Category;
        percentage: number;
    }>;
    totalGainLossPercent: number;
} {
    return {
        totalValue: value.totalValue,
        totalCost: value.totalCost,
        dailyChange: value.dailyChange,
        totalGainLoss: value.totalGainLoss,
        allocation: from_candid_vec_n32(_uploadFile, _downloadFile, value.allocation),
        totalGainLossPercent: value.totalGainLossPercent
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: number;
    category: _Category;
    percentage: number;
}): {
    value: number;
    category: Category;
    percentage: number;
} {
    return {
        value: value.value,
        category: from_candid_Category_n16(_uploadFile, _downloadFile, value.category),
        percentage: value.percentage
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Stock: null;
} | {
    RealEstate: null;
} | {
    Cash: null;
} | {
    Commodity: null;
} | {
    Forex: null;
} | {
    Crypto: null;
}): Category {
    return "Stock" in value ? Category.Stock : "RealEstate" in value ? Category.RealEstate : "Cash" in value ? Category.Cash : "Commodity" in value ? Category.Commodity : "Forex" in value ? Category.Forex : "Crypto" in value ? Category.Crypto : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Buy: null;
} | {
    Withdraw: null;
} | {
    Deposit: null;
} | {
    Sell: null;
}): TxType {
    return "Buy" in value ? TxType.Buy : "Withdraw" in value ? TxType.Withdraw : "Deposit" in value ? TxType.Deposit : "Sell" in value ? TxType.Sell : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Public__1>): Array<Public__1> {
    return value.map((x)=>from_candid_Public__1_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Public__3>): Array<Public__3> {
    return value.map((x)=>from_candid_Public__3_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Holding>): Array<Holding> {
    return value.map((x)=>from_candid_Holding_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    value: number;
    category: _Category;
    percentage: number;
}>): Array<{
    value: number;
    category: Category;
    percentage: number;
}> {
    return value.map((x)=>from_candid_record_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n35(_uploadFile, _downloadFile, x));
}
function to_candid_AddTransactionInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddTransactionInput): _AddTransactionInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_AssetImport_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetImport): _AssetImport {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PortfolioImportInput_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PortfolioImportInput): _PortfolioImportInput {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_Public__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Public__1): _Public__1 {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionImport_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionImport): _TransactionImport {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_TxType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxType): _TxType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    note: string;
    createdAt: bigint;
    currency: string;
    category: Category;
    manualPrice: number;
    symbol: string;
}): {
    id: bigint;
    name: string;
    note: string;
    createdAt: bigint;
    currency: string;
    category: _Category;
    manualPrice: number;
    symbol: string;
} {
    return {
        id: value.id,
        name: value.name,
        note: value.note,
        createdAt: value.createdAt,
        currency: value.currency,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        manualPrice: value.manualPrice,
        symbol: value.symbol
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assets: Array<AssetImport>;
    transactions: Array<TransactionImport>;
}): {
    assets: Array<_AssetImport>;
    transactions: Array<_TransactionImport>;
} {
    return {
        assets: to_candid_vec_n39(_uploadFile, _downloadFile, value.assets),
        transactions: to_candid_vec_n42(_uploadFile, _downloadFile, value.transactions)
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    note: string;
    currency: string;
    category: Category;
    manualPrice: number;
    symbol: string;
}): {
    name: string;
    note: string;
    currency: string;
    category: _Category;
    manualPrice: number;
    symbol: string;
} {
    return {
        name: value.name,
        note: value.note,
        currency: value.currency,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        manualPrice: value.manualPrice,
        symbol: value.symbol
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fee: number;
    assetId: bigint;
    date: bigint;
    note: string;
    currency: string;
    quantity: number;
    txType: TxType;
    price: number;
}): {
    fee: number;
    assetId: bigint;
    date: bigint;
    note: string;
    currency: string;
    quantity: number;
    txType: _TxType;
    price: number;
} {
    return {
        fee: value.fee,
        assetId: value.assetId,
        date: value.date,
        note: value.note,
        currency: value.currency,
        quantity: value.quantity,
        txType: to_candid_TxType_n7(_uploadFile, _downloadFile, value.txType),
        price: value.price
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    fee: number;
    assetId: bigint;
    date: bigint;
    note: string;
    createdAt: bigint;
    currency: string;
    quantity: number;
    txType: TxType;
    price: number;
}): {
    id: bigint;
    fee: number;
    assetId: bigint;
    date: bigint;
    note: string;
    createdAt: bigint;
    currency: string;
    quantity: number;
    txType: _TxType;
    price: number;
} {
    return {
        id: value.id,
        fee: value.fee,
        assetId: value.assetId,
        date: value.date,
        note: value.note,
        createdAt: value.createdAt,
        currency: value.currency,
        quantity: value.quantity,
        txType: to_candid_TxType_n7(_uploadFile, _downloadFile, value.txType),
        price: value.price
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Stock: null;
} | {
    RealEstate: null;
} | {
    Cash: null;
} | {
    Commodity: null;
} | {
    Forex: null;
} | {
    Crypto: null;
} {
    return value == Category.Stock ? {
        Stock: null
    } : value == Category.RealEstate ? {
        RealEstate: null
    } : value == Category.Cash ? {
        Cash: null
    } : value == Category.Commodity ? {
        Commodity: null
    } : value == Category.Forex ? {
        Forex: null
    } : value == Category.Crypto ? {
        Crypto: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxType): {
    Buy: null;
} | {
    Withdraw: null;
} | {
    Deposit: null;
} | {
    Sell: null;
} {
    return value == TxType.Buy ? {
        Buy: null
    } : value == TxType.Withdraw ? {
        Withdraw: null
    } : value == TxType.Deposit ? {
        Deposit: null
    } : value == TxType.Sell ? {
        Sell: null
    } : value;
}
function to_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AssetImport>): Array<_AssetImport> {
    return value.map((x)=>to_candid_AssetImport_n40(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TransactionImport>): Array<_TransactionImport> {
    return value.map((x)=>to_candid_TransactionImport_n43(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
